name: dice
description: "Dice Target"
publish_to: 'none'
version: 1.1.2+7

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Audio SFX
  audioplayers: ^6.5.1

  # Persistent settings
  shared_preferences: ^2.2.3

  # Confetti animation
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/sfx/
    - assets/branding/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/DiceTarget_AppIcon_1024_universal.png"
  adaptive_icon_background: "#0F1118"
  adaptive_icon_foreground: "assets/DiceTarget_AppIcon_1024_universal.png"

flutter_native_splash:
  color: "#090B18"
  image: assets/DiceTarget_AppIcon_1024_universal.png

  android: true
  ios: true

  android_12:
    color: "#090B18"
    image: assets/DiceTarget_AppIcon_1024_universal.png